# Generated by Django 2.0.6 on 2018-12-31 14:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p04_001', models.CharField(max_length=50)),
                ('p04_002', models.CharField(max_length=50)),
                ('p04_003', models.CharField(max_length=50)),
                ('p04_004', models.CharField(max_length=50)),
                ('p04_005', models.CharField(max_length=50)),
                ('p04_006', models.CharField(max_length=50)),
                ('p04_007', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': '東京医療施設データ ',
                'verbose_name': '東京医療施設データ ',
            },
        ),
    ]
