# Generated by Django 2.0.6 on 2018-12-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='p04_001',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medical',
            name='p04_002',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medical',
            name='p04_003',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medical',
            name='p04_004',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medical',
            name='p04_005',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medical',
            name='p04_006',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medical',
            name='p04_007',
            field=models.CharField(max_length=255),
        ),
    ]
